### ISSUE TITLE
brew install fail,How to fix it?

### ISSUE THREAD

**Issue by seekting** [uber/nanoscope#65]
seekting@seekting:~$ brew install nanoscope
Error: cannot load such file -- os/linux/glibc
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/seekting/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:1:in `load_formula'
/home/seekting/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/seekting/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/seekting/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/seekting/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/seekting/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/seekting/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/seekting/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/seekting/.linuxbrew/Library/Homebrew/formula.rb:1186:in `[]'
/home/seekting/.linuxbrew/Library/Homebrew/cmd/install.rb:200:in `check_ld_so_symlink'
/home/seekting/.linuxbrew/Library/Homebrew/cmd/install.rb:213:in `perform_preinstall_checks'
/home/seekting/.linuxbrew/Library/Homebrew/cmd/install.rb:91:in `install'
/home/seekting/.linuxbrew/Library/brew.rb:84:in `<main>'

**Comment by mirfansulaiman** [comment]
Hi, 
Are you using debian/ubuntu? You need install this first
**Debian or Ubuntu**
`sudo apt-get install build-essential curl file git`
**Fedora**
`sudo dnf groupinstall 'Development Tools' && sudo dnf install curl file git`
**CentOS or Red Hat**
`sudo yum groupinstall 'Development Tools' && sudo yum install curl file git`

**Comment by Twyrch** [comment]
I have the same issue and I've already installed the build-essential and the problem remains.

**Comment by Twyrch** [comment]
When I run Brew Doctor, this is the output but I don't know where I should go to change the entries.
![brew doctor](https://user-images.githubusercontent.com/45364428/50564949-de725100-0cf7-11e9-9c7b-7fcc3539f0e1.PNG)

**Comment by hugobuddel** [comment]
See https://github.com/Linuxbrew/brew/issues/936#issuecomment-464228560

````
brew update
brew vendor-install ruby
brew update
````

using brew from ubuntu 16.04

**Comment by AimableHonorable** [comment]
> See [Linuxbrew/brew#936 (comment)](https://github.com/Linuxbrew/brew/issues/936#issuecomment-464228560)
> 
> ```
> brew update
> brew vendor-install ruby
> brew update
> ```
> 
> using brew from ubuntu 16.04

This worked for me

**Comment by PankajPrakashh** [comment]
```
brew update
brew vendor-install ruby
brew update
```

worked in ubuntu 19.10
