### ISSUE TITLE
`nanoscope emulator` exits with an error

### ISSUE THREAD

**Issue by ragunathjawahar** [uber/nanoscope#87]
```
Zip already downloaded: /Users/ragunathjawahar/.nanoscope/roms/L2Xyj8R6fKIhj37bsgVYYg==...
Launching emulator...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
cp: /Users/ragunathjawahar/Library/Android/sdk/system-images/android-25/default/x86: No such file or directory
./emulator.sh: line 31: /Users/ragunathjawahar/Library/Android/sdk/system-images/nanoscope/SOURCE: Not a directory
sed: /Users/ragunathjawahar/Library/Android/sdk/system-images/nanoscope/advancedFeatures.ini: Not a directory
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.AvdManagerCli.run(AvdManagerCli.java:213)
	at com.android.sdklib.tool.AvdManagerCli.main(AvdManagerCli.java:200)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
./emulator.sh: line 37: /Users/ragunathjawahar/.android/avd/nanoscope.avd/config.ini: No such file or directory
sed: /Users/ragunathjawahar/.android/avd/nanoscope.avd/config.ini: No such file or directory
sed: /Users/ragunathjawahar/Library/Android/sdk/system-images/nanoscope/package.xml: Not a directory
emulator:Android emulator version 26.0.3.0 (build_id 3965150)
emulator:Found AVD name 'nanoscope'
PANIC: Unknown AVD name [nanoscope], use -list-avds to see valid list.
HOME is defined but there is no file nanoscope.ini in $HOME/.android/avd
(Note: Directories are searched in the order $ANDROID_AVD_HOME, $ANDROID_SDK_HOME/avd, and $HOME/.android/avd)
```

**Comment by abhayptp** [comment]
+1, facing same issue.

**Comment by Abhityagi16** [comment]
Switch to Java8. It will work

**Comment by tricknology** [comment]
Right, this is usually the sign you have a compatibility issue: ` java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema`
